### ISSUE TITLE
What version of BGAPI does this library apply to.

### ISSUE THREAD

**Issue by Gerriko** [xloem/bglibpp#1]
Is this library for BGAPI version 3.1?

**Comment by xloem** [comment]
This is intended for BLED112 dongles, so it might be whatever version they use, I'm not sure; do you know?

The code is ported from 153492557b916f600f6a12c72426dd3c01999bb8, which is from [a zip](https://www.silabs.com/content/usergenerated/asi/cloud/attachments/siliconlabs/en/community/wireless/bluetooth/forum/jcr:content/content/primary/qna/bled112_bgapi_orbg-CxSa/hi_yes_you_re_righ-rP5z/src.zip) that an silabs employee [posted to a forum in 2017](https://www.silabs.com/community/wireless/bluetooth/forum.topic.html/bled112_bgapi_orbg-CxSa).  I don't actually use this device much myself and just worked off that zip.

**Comment by Gerriko** [comment]
Great. Thanks for the clarification.
